package com.mit.bodhiq.utils;

import android.text.TextUtils;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.mit.bodhiq.data.model.EmergencyContact;
import com.mit.bodhiq.data.model.UserProfile;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Builder for Emergency QR code payload
 * Format: Human-readable summary followed by structured JSON
 */
public class EmergencyPayloadBuilder {
    
    private static final int MAX_PAYLOAD_SIZE = 3 * 1024; // 3 KB limit
    private static final String SCHEMA_VERSION = "medical-agent.v1";
    private static final Gson gson = new GsonBuilder().setPrettyPrinting().create();
    
    /**
     * Build emergency payload with human-readable summary + structured JSON
     */
    public static String build(UserProfile profile) {
        // Build human-readable summary first
        String summary = buildHumanReadableSummary(profile);
        
        // Build structured JSON data
        String jsonData = buildStructuredJson(profile);
        
        // Combine: summary + separator + JSON
        return summary + "\n\n---STRUCTURED-DATA---\n" + jsonData;
    }
    
    /**
     * Build human-readable summary for generic QR scanners
     */
    private static String buildHumanReadableSummary(UserProfile profile) {
        StringBuilder summary = new StringBuilder();
        summary.append("🚨 EMERGENCY MEDICAL INFORMATION 🚨\n\n");
        
        // Essential information in clear format
        summary.append("Name: ").append(profile.getFullName()).append("\n");
        
        if (!TextUtils.isEmpty(profile.getBloodGroup())) {
            summary.append("Blood Group: ").append(profile.getBloodGroup()).append("\n");
        }
        
        if (!TextUtils.isEmpty(profile.getAllergies())) {
            summary.append("⚠️ Allergies: ").append(profile.getAllergies()).append("\n");
        }
        
        if (!TextUtils.isEmpty(profile.getEmergencyContact())) {
            summary.append("Emergency Contact: ").append(profile.getEmergencyContact()).append("\n");
        }
        
        if (!TextUtils.isEmpty(profile.getDateOfBirth())) {
            summary.append("DOB: ").append(profile.getDateOfBirth()).append("\n");
        }
        
        if (!TextUtils.isEmpty(profile.getPhoneNumber())) {
            summary.append("Phone: ").append(profile.getPhoneNumber()).append("\n");
        }
        
        summary.append("\nGenerated by BodhIQ Medical Agent");
        
        return summary.toString();
    }
    
    /**
     * Build structured JSON payload for machine readability
     */
    private static String buildStructuredJson(UserProfile profile) {
        Map<String, Object> payload = new HashMap<>();
        
        // Schema metadata
        payload.put("schema", SCHEMA_VERSION);
        payload.put("type", "emergency-medical-info");
        payload.put("version", 1);
        
        // Patient information
        Map<String, Object> patient = new HashMap<>();
        patient.put("fullName", profile.getFullName());
        patient.put("userId", profile.getUserId());
        
        if (!TextUtils.isEmpty(profile.getDateOfBirth())) {
            patient.put("dateOfBirth", profile.getDateOfBirth());
        }
        
        if (!TextUtils.isEmpty(profile.getGender())) {
            patient.put("gender", profile.getGender());
        }
        
        if (!TextUtils.isEmpty(profile.getAge())) {
            patient.put("age", profile.getAge());
        }
        
        payload.put("patient", patient);
        
        // Medical information
        Map<String, Object> medical = new HashMap<>();
        
        if (!TextUtils.isEmpty(profile.getBloodGroup())) {
            medical.put("bloodGroup", profile.getBloodGroup());
        }
        
        // Parse allergies into structured list
        if (!TextUtils.isEmpty(profile.getAllergies())) {
            List<String> allergies = parseCommaSeparated(profile.getAllergies());
            if (!allergies.isEmpty()) {
                medical.put("allergies", allergies);
            }
        }
        
        // Medical conditions (placeholder for future expansion)
        List<String> conditions = new ArrayList<>();
        if (!conditions.isEmpty()) {
            medical.put("conditions", conditions);
        }
        
        payload.put("medical", medical);
        
        // Contact information
        Map<String, Object> contacts = new HashMap<>();
        
        if (!TextUtils.isEmpty(profile.getPhoneNumber())) {
            contacts.put("primaryPhone", profile.getPhoneNumber());
        }
        
        if (!TextUtils.isEmpty(profile.getEmail())) {
            contacts.put("email", profile.getEmail());
        }
        
        // Emergency contacts
        List<Map<String, String>> emergencyContacts = new ArrayList<>();
        if (!TextUtils.isEmpty(profile.getEmergencyContact())) {
            Map<String, String> contact = new HashMap<>();
            contact.put("name", "Emergency Contact");
            contact.put("relationship", "Primary");
            contact.put("phone", profile.getEmergencyContact());
            emergencyContacts.add(contact);
        }
        
        if (!emergencyContacts.isEmpty()) {
            contacts.put("emergency", emergencyContacts);
        }
        
        payload.put("contacts", contacts);
        
        // Metadata
        Map<String, Object> metadata = new HashMap<>();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.US);
        metadata.put("generatedAt", sdf.format(new Date()));
        metadata.put("source", "BodhIQ Medical Agent");
        metadata.put("dataVersion", 1);
        
        payload.put("metadata", metadata);
        
        return gson.toJson(payload);
    }
    
    /**
     * Build compact emergency payload (essential info only)
     */
    public static String buildCompact(UserProfile profile) {
        StringBuilder compact = new StringBuilder();
        compact.append("🚨 EMERGENCY INFO 🚨\n");
        compact.append(profile.getFullName());
        
        if (!TextUtils.isEmpty(profile.getBloodGroup())) {
            compact.append(" | ").append(profile.getBloodGroup());
        }
        
        if (!TextUtils.isEmpty(profile.getAllergies())) {
            compact.append(" | ⚠️ ").append(profile.getAllergies());
        }
        
        if (!TextUtils.isEmpty(profile.getEmergencyContact())) {
            compact.append(" | 📞 ").append(profile.getEmergencyContact());
        }
        
        // Minimal JSON
        compact.append("\n\n");
        Map<String, Object> minimalData = new HashMap<>();
        minimalData.put("schema", SCHEMA_VERSION);
        minimalData.put("name", profile.getFullName());
        
        if (!TextUtils.isEmpty(profile.getBloodGroup())) {
            minimalData.put("blood", profile.getBloodGroup());
        }
        
        if (!TextUtils.isEmpty(profile.getAllergies())) {
            minimalData.put("allergies", parseCommaSeparated(profile.getAllergies()));
        }
        
        if (!TextUtils.isEmpty(profile.getEmergencyContact())) {
            minimalData.put("contact", profile.getEmergencyContact());
        }
        
        compact.append(new Gson().toJson(minimalData));
        return compact.toString();
    }
    
    /**
     * Check if payload exceeds size limit
     */
    public static boolean exceedsSizeLimit(String payload) {
        return payload.getBytes().length > MAX_PAYLOAD_SIZE;
    }
    
    /**
     * Get payload size in bytes
     */
    public static int getPayloadSize(String payload) {
        return payload.getBytes().length;
    }
    
    /**
     * Get schema version
     */
    public static String getSchemaVersion() {
        return SCHEMA_VERSION;
    }
    
    /**
     * Parse comma-separated string into list
     */
    private static List<String> parseCommaSeparated(String input) {
        List<String> result = new ArrayList<>();
        if (TextUtils.isEmpty(input)) {
            return result;
        }
        
        String[] parts = input.split(",");
        for (String part : parts) {
            String trimmed = part.trim();
            if (!trimmed.isEmpty()) {
                result.add(trimmed);
            }
        }
        return result;
    }
    
    /**
     * Build vCard format as alternative
     */
    public static String buildVCard(UserProfile profile) {
        StringBuilder vcard = new StringBuilder();
        vcard.append("BEGIN:VCARD\n");
        vcard.append("VERSION:3.0\n");
        vcard.append("FN:").append(profile.getFullName()).append("\n");
        
        if (!TextUtils.isEmpty(profile.getEmail())) {
            vcard.append("EMAIL:").append(profile.getEmail()).append("\n");
        }
        
        if (!TextUtils.isEmpty(profile.getPhoneNumber())) {
            vcard.append("TEL:").append(profile.getPhoneNumber()).append("\n");
        }
        
        if (!TextUtils.isEmpty(profile.getEmergencyContact())) {
            vcard.append("TEL;TYPE=EMERGENCY:").append(profile.getEmergencyContact()).append("\n");
        }
        
        if (!TextUtils.isEmpty(profile.getBloodGroup())) {
            vcard.append("NOTE:Blood Group: ").append(profile.getBloodGroup());
            if (!TextUtils.isEmpty(profile.getAllergies())) {
                vcard.append(" | Allergies: ").append(profile.getAllergies());
            }
            vcard.append("\n");
        }
        
        vcard.append("END:VCARD");
        return vcard.toString();
    }
}
